/**
 * The promotional band across the top of the home page — "the next Football 101
 * is on the 8th, here are the tickets" — switched on and written in the Studio.
 *
 * This is the one renderer on the site that draws its own markup rather than
 * refilling the design's (compare tools/news-index.js and tools/episode-index.js,
 * which only ever put different words inside markup a designer drew). Two
 * reasons, and the first is the binding one:
 *
 *  - The home page's copy is bound to the design **by position** —
 *    `homePage.reelHeading` is "the first h2 of the third section", see
 *    tools/page-text.js. A new section at the top of that block renumbers every
 *    binding under it, and the failure mode is not a crash: it is a heading
 *    rendering the wrong sentence. Drawing the band here, after applyText() has
 *    run, means the design is not touched and nothing moves.
 *  - There is nothing to refill. A band that appears a few times a year has no
 *    exemplar in the design to copy, and inventing one there for the sake of
 *    this renderer would put the trap above into the file permanently.
 *
 * The trade is that this file owns four inline styles, so they are written from
 * the design's own vocabulary and nothing else: Archivo at the site's uppercase
 * label size and tracking, `var(--accent)` for the ground (the same red the
 * "Event Series" eyebrow uses on the section further down the page), and the
 * `max-width:1280px; margin:0 auto` container every other band on the site uses
 * — which is also what picks up the design's mobile gutter rule, since the
 * helmet's `[style*="margin:0 auto"]` selector is what sets it.
 *
 * `style-hover` is left in the markup deliberately: build-static.js lifts it
 * into a real `.hv-N` rule in css/site.css with the rest of them, so the band's
 * hover is generated by the same machinery as every other link on the site and
 * cannot drift from it. The cost is that switching the band on inserts a rule
 * partway through the `hv-N` numbering and shifts the rest along, so every page
 * changes — harmlessly, since the stylesheet and the pages come out of the same
 * build and check.js verifies every class a page names, but it is why a toggle
 * shows up as a one-line diff site-wide rather than on index.html alone.
 */

const escapeHtml = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

const escapeAttr = (s) => escapeHtml(s).replace(/"/g, '&quot;');

/** Where the band goes: immediately above the home page's hero photograph. */
const ANCHOR = '<section data-r="hero"';

/**
 * Is there a banner to draw?
 *
 * Switched on is not enough. A band with no link is a sentence about an event
 * with no way to reach it, which is the same failure the Eventbrite CTA shipped
 * with in its first release — see EVENTBRITE_URL in build-static.js. The Studio
 * refuses to publish that combination (the `eventBanner` object validates it),
 * and this is the second line: an incomplete banner is dropped rather than half
 * drawn, and the caller says so in the build log.
 */
function bannerFrom(homePage) {
  const b = (homePage && homePage.eventBanner) || null;
  if (!b || !b.enabled) return null;

  const text = String(b.text || '').trim();
  const label = String(b.linkLabel || '').trim();
  const url = String(b.url || '').trim();
  if (!text || !label || !url) {
    return { incomplete: true, missing: [
      !text && 'message',
      !label && 'button text',
      !url && 'link',
    ].filter(Boolean) };
  }

  return { eyebrow: String(b.eyebrow || '').trim(), text, label, url };
}

/**
 * Draw the band.
 *
 * One flex row that wraps: on a phone the three parts stack and centre, on a
 * desktop they sit on one line. No grid — the design's mobile rule collapses
 * every `grid-template-columns` to a single column, which is right for the
 * page's content bands and wrong for a strip that is meant to stay a strip.
 */
function bannerHtml({ eyebrow, text, label, url }) {
  const eyebrowSpan = eyebrow
    ? `\n        <span style="font-family:Archivo, sans-serif; font-size:11.5px; font-weight:600; letter-spacing:0.2em; text-transform:uppercase; color:rgba(255,255,255,.7); white-space:nowrap">${escapeHtml(eyebrow)}</span>`
    : '';

  return `    <aside aria-label="Upcoming event" style="background:var(--accent, #AB0520); color:#fff">
      <div style="max-width:1280px; margin:0 auto; padding:15px 40px; display:flex; align-items:center; justify-content:center; flex-wrap:wrap; gap:8px 22px; text-align:center">${eyebrowSpan}
        <span style="font-family:Archivo, sans-serif; font-size:16px; font-weight:500; line-height:1.45; color:#fff">${escapeHtml(text)}</span>
        <a href="${escapeAttr(url)}" style="font-family:Archivo, sans-serif; font-size:12.5px; font-weight:700; letter-spacing:0.12em; text-transform:uppercase; color:#fff; border-bottom:2px solid rgba(255,255,255,.55); padding-bottom:4px; white-space:nowrap" style-hover="border-bottom-color:#fff; color:#fff">${escapeHtml(label)}</a>
      </div>
    </aside>
`;
}

/**
 * Insert the band into the home block, above the hero.
 *
 * Call this AFTER applyText() and applyPhotos() and BEFORE transform() — after,
 * because both of those address the block by position and this adds an element;
 * before, because transform() is what turns `style-hover` into a class and what
 * would otherwise leave DC syntax in the page for check.js to find.
 *
 * Returns `{ html, state }`: `state` is 'off', 'incomplete' or 'on', so the
 * build log can distinguish "Ricky has not switched it on" from "Ricky switched
 * it on and it did not appear", which is the only one of the three that needs
 * explaining to anybody.
 */
function renderEventBanner(html, homePage) {
  const banner = bannerFrom(homePage);
  if (!banner) return { html, state: 'off' };
  if (banner.incomplete) {
    return { html, state: 'incomplete', missing: banner.missing };
  }

  const at = html.indexOf(ANCHOR);
  if (at === -1) {
    // The hero is the anchor because it is the first thing on the page and it
    // is marked (`data-r="hero"`) for the design's own mobile rules, so it is
    // not a selector invented here. If it has been renamed, stop: putting the
    // band anywhere else on the page is worse than not shipping it.
    throw new Error(
      'event banner: no `' + ANCHOR + '` in the home block to sit above.\n' +
        'The design has moved — find what now opens the home page and update ANCHOR in tools/event-banner.js.'
    );
  }

  // Back up over the hero's own indentation so the band lands on its own line.
  const lineStart = html.lastIndexOf('\n', at) + 1;
  return {
    html: html.slice(0, lineStart) + bannerHtml(banner) + html.slice(lineStart),
    state: 'on',
  };
}

module.exports = { renderEventBanner };
